---
- name: restarts service
  become: yes
  become_user: vertigo
  systemd:
    scope: user
    service: psychopy-session-webserver
    daemon_reload: yes
    state: restarted

- name: trigger udev rules
  shell: |
    udevadm control --reload && udevadm trigger
