---
- name: restarts psychopy-session-webserver service
  become: yes
  become_user: vertigo
  systemd:
    scope: user
    service: psychopy-session-webserver
    daemon_reload: yes
    enabled: yes
    state: restarted

- name: trigger udev rules
  shell: |
    udevadm control --reload && udevadm trigger

- name: restarts vertigo-camera service
  systemd:
    service: vertigo-camera
    daemon_reload: yes
    state: restarted
    enabled: yes
