---
- name: install required packages
  apt:
    name:
      - libboost-dev
      - libgnutls28-dev
      - openssl
      - libtiff-dev
      - pybind11-dev
      - qtbase5-dev
      - libqt5core5a
      - libqt5widgets5
      - meson
      - cmake
      - python3-yaml
      - python3-ply
      - libglib2.0-dev
      - libgstreamer-plugins-base1.0-dev
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-rtsp

- name: download patched libcamerasrc sources
  git:
    repo: https://github.com/iNkawuVervetProject/libcamera
    dest: /usr/local/src/libcamera
    version: dev/custom

- name: build patched libcamera
  shell:
    chdir: /usr/local/src/libcamera
    cmd: |
      meson setup build --buildtype=release -Dpipelines=rpi/vc4,rpi/pisp -Dipas=rpi/vc4,rpi/pisp -Dv4l2=true -Dgstreamer=enabled -Dtest=false -Dlc-compliance=disabled -Dcam=disabled -Dqcam=disabled -Ddocumentation=disabled -Dpycamera=enabled
      ninja -C build install


- name: upload inkawuvp_vertigo_camera package
  synchronize:
    src: vertigo-camera/
    dest: /usr/local/src/inkawuvp-vertigo-camera
    rsync_opts:
      - '--exclude=__pycache__/'
      - '--exclude=*.egg-info/'
      - '--exclude=dist'
      - '--exclude=*.mp4'
      - '--exclude=*.pickle'
      - '--exclude=*~'
      - '--exclude=.direnv'
      - '--exclude=venv'

- name: installs inkawuvp_vertigo_camera package
  pip:
    extra_args: --upgrade -f /usr/local/wheels
    name:
      - pip
      - /usr/local/src/inkawuvp-vertigo-camera
    virtualenv: /usr/local/src/inkawuvp-vertigo-camera/venv
    virtualenv_command: /usr/bin/python -m venv
  notify: restarts vertigo-camera service

- name: ensure local bin exists
  file:
    path: /usr/local/bin
    state: directory

- name: install vertigo-camera-webservice.sh
  copy:
    src: vertigo-camera-service.sh
    dest: /usr/local/bin/vertigo-camera-service.sh
    mode: 0755
  notify: restarts vertigo-camera service

- name: add service files
  copy:
    src: vertigo-camera.service
    dest: /etc/systemd/system/vertigo-camera.service
  notify: restarts vertigo-camera service

- name: add mediamtx configuration file
  copy:
    src: mediamtx.yml
    dest: /usr/local/src/libcamera/mediamtx.yml
