---
- name: ensure destination dir exists
  file:
    path: /usr/local/src/webui
    state: directory

- name: uploads webui source files
  synchronize:
    src: webui/
    dest: /usr/local/src/webui
    rsync_opts:
      - '--exclude=node_modules'
      - '--exclude=.svelte-kit'
      - '--exclude=build'
      - '--exclude=package'
      - '--exclude=routes.yml'
      - '--exclude=docker-compose.yml'
      - '--exclude=*~'
      - '--delete'

- name: installs reverse proxy configuration
  template:
    src: routes.yml.j2
    dest: /usr/local/src/webui/routes.yml

- name: installs docker-compose
  copy:
    src: docker-compose.yml
    dest: /usr/local/src/webui/docker-compose.yml

- name: boots via docker compose
  community.docker.docker_compose_v2:
    project_src: /usr/local/src/webui
    state: present
    remove_orphans: yes
    pull: always
    build: always
