services:
  svelte:
    image: svelte
    build: ./
    container_name: svelte
    network_mode: host
    environment:
      - PROTOCOL_HEADER=x-forwarded-proto
      - HOST_HEADER=x-forwarded-host
    restart: 'unless-stopped'

  mediamtx:
    image: bluenviron/mediamtx:latest
    network_mode: host
    volumes:
      - /usr/local/src/libcamera/mediamtx.yml:/mediamtx.yml:ro

  traefik:
    image: traefik:latest
    command:
      - --entrypoints.web.address=:80
      - --providers.file.filename=/routes.yml
      - --api.insecure=true
      - --accesslog=false
    ports:
      - "80:80"
      - "8080:8080"
    extra_hosts:
      - "vertigo-localhost:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./routes.yml:/routes.yml
    restart: 'unless-stopped'
